# Generated by Django 6.1.1 on 2026-09-30 12:02

import django.core.validators
import django.db.models.deletion
import jobs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='INN')),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=16)),
                ('description', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('blacklist_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('industry', models.CharField(choices=[('construction', 'Сохтмон'), ('warehouse', 'Анбор'), ('delivery', 'Расонидан'), ('taxi', 'Таксӣ ва ронандагӣ'), ('trade', 'Савдо'), ('food', 'Ошхона ва қаҳвахона'), ('cleaning', 'Тозакунӣ'), ('agriculture', 'Кишоварзӣ'), ('manufacturing', 'Истеҳсолот'), ('other', 'Дигар')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('salary_from', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_to', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_period', models.CharField(choices=[('month', 'Per month'), ('day', 'Per day'), ('hour', 'Per hour')], default='month', max_length=10)),
                ('schedule', models.CharField(blank=True, max_length=100)),
                ('housing_provided', models.BooleanField(default=False)),
                ('meals_provided', models.BooleanField(default=False)),
                ('helps_with_documents', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('promoted_until', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(default=jobs.models.default_job_expiry)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.employer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('viewed', 'Viewed'), ('invited', 'Invited'), ('rejected', 'Rejected')], default='sent', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1940), django.core.validators.MaxValueValidator(2012)])),
                ('city', models.CharField(max_length=100)),
                ('industry', models.CharField(choices=[('construction', 'Сохтмон'), ('warehouse', 'Анбор'), ('delivery', 'Расонидан'), ('taxi', 'Таксӣ ва ронандагӣ'), ('trade', 'Савдо'), ('food', 'Ошхона ва қаҳвахона'), ('cleaning', 'Тозакунӣ'), ('agriculture', 'Кишоварзӣ'), ('manufacturing', 'Истеҳсолот'), ('other', 'Дигар')], max_length=20)),
                ('profession', models.CharField(max_length=150)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('russian_level', models.CharField(choices=[('none', 'Намедонам'), ('basic', 'Каме'), ('good', 'Хуб'), ('fluent', 'Озод')], default='basic', max_length=10)),
                ('has_patent', models.BooleanField(default=False)),
                ('about', models.TextField(blank=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField(blank=True)),
                ('salary_not_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_reviews', to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='jobs.employer')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('employer', 'author'), name='one_review_per_employer')],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['city', 'industry'], name='jobs_job_city_712e84_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(fields=('job', 'applicant'), name='one_application_per_job'),
        ),
    ]
