# Generated by Django 6.1.1 on 2026-10-01 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='external_id',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='source',
            field=models.CharField(choices=[('site', 'Muhojir.tj'), ('trudvsem', 'Работа России')], default='site', max_length=20),
        ),
        migrations.AddField(
            model_name='employer',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='external_id',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='job',
            name='external_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('site', 'Muhojir.tj'), ('trudvsem', 'Работа России')], default='site', max_length=20),
        ),
        migrations.AlterField(
            model_name='employer',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employer',
            name='phone',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['source'], name='jobs_job_source_e2155e_idx'),
        ),
    ]
