# Generated by Django 6.1.1 on 2026-10-01 13:49

from django.db import migrations, models


def drop_site_jobs(apps, schema_editor):
    # Employers no longer exist on the site: their ads and company profiles go; imported ones stay.
    apps.get_model("jobs", "Job").objects.filter(source="site").delete()
    apps.get_model("jobs", "Employer").objects.filter(source="site").delete()



class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_imported_jobs'),
    ]

    operations = [
        migrations.RunPython(drop_site_jobs, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='jobapplication',
            name='one_application_per_job',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='job',
            name='promoted_until',
        ),
        migrations.AlterField(
            model_name='employer',
            name='source',
            field=models.CharField(choices=[('trudvsem', 'Работа России')], default='trudvsem', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('trudvsem', 'Работа России')], default='trudvsem', max_length=20),
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='job',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
