# Generated by Django 6.1.1 on 2026-10-01 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_only_imported_jobs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(blank=True, choices=[('construction', 'Сохтмон'), ('warehouse', 'Анбор'), ('delivery', 'Расонидан'), ('taxi', 'Таксӣ ва ронандагӣ'), ('trade', 'Савдо'), ('food', 'Ошхона ва қаҳвахона'), ('cleaning', 'Тозакунӣ'), ('agriculture', 'Кишоварзӣ'), ('manufacturing', 'Истеҳсолот'), ('other', 'Дигар')], max_length=20)),
                ('min_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('housing_provided', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'job'), name='one_save_per_job')],
            },
        ),
    ]
