import forms from "@tailwindcss/forms";

// Colors, sizes and type scale from the Muhojir.tj design (Material 3 style token names).
// Blue is the main color and red the accent; "warning" (amber) is only for deadlines that end soon,
// so they never look like "expired" (error red).
/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        // Dark blue of the sidebar and the patterned banners.
        navy: "#0d2f73",
        "on-navy": "#dbe6ff",
        "navy-muted": "#b9cdf6",
        primary: "#1447a8",
        "on-primary": "#ffffff",
        "primary-container": "#1e63d6",
        "on-primary-container": "#e3ecff",
        "primary-fixed": "#dbe6ff",
        "on-primary-fixed": "#001a43",
        secondary: "#c1121f",
        "on-secondary": "#ffffff",
        "secondary-container": "#e5484d",
        "on-secondary-container": "#ffffff",
        "secondary-fixed": "#ffe1e3",
        "on-secondary-fixed": "#410006",
        warning: "#8a5100",
        "on-warning": "#ffffff",
        "warning-container": "#f59e0b",
        "on-warning-container": "#3d2400",
        "warning-fixed": "#ffe8c7",
        "on-warning-fixed": "#2e1800",
        tertiary: "#005f26",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#007a33",
        "tertiary-fixed": "#7ffc97",
        "on-tertiary-fixed": "#002109",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#f4f6fb",
        surface: "#f8f9ff",
        "on-surface": "#0b1c30",
        "on-surface-variant": "#3e4947",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e5eeff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d3e4fe",
        "inverse-surface": "#213145",
        "inverse-on-surface": "#eaf1ff",
        outline: "#6e7977",
        "outline-variant": "#bdc9c6",
      },
      fontFamily: {
        sans: ['"Noto Sans"', "system-ui", "sans-serif"],
        // Headings and big numbers (design "Нақш"). Noto has every Tajik letter: ӣ ӯ ҳ қ ғ ҷ.
        display: ['"Noto Serif Display"', "Georgia", "serif"],
      },
      fontSize: {
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "700" }],
        "label-md": ["13px", { lineHeight: "18px", fontWeight: "600" }],
        "label-lg": ["15px", { lineHeight: "20px", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "18px" }],
        "body-md": ["15px", { lineHeight: "22px" }],
        "body-lg": ["16px", { lineHeight: "24px" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-xl": ["36px", { lineHeight: "44px", fontWeight: "700" }],
      },
    },
  },
  plugins: [forms],
};
