# Generated by Django 6.1.1 on 2026-10-01 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_telegram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telegram_chat_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_link_code',
        ),
    ]
