# Generated by Django 6.1.1 on 2026-10-01 13:49

from django.db import migrations, models


def employers_to_migrants(apps, schema_editor):
    apps.get_model("accounts", "User").objects.filter(role="employer").update(role="migrant")



class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_telegram'),
    ]

    operations = [
        migrations.RunPython(employers_to_migrants, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('migrant', 'Migrant'), ('admin', 'Admin')], default='migrant', max_length=20),
        ),
    ]
