# Generated by Django 6.1.1 on 2026-10-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_push_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('migrant', 'Migrant'), ('editor', 'Editor'), ('admin', 'Admin')], default='migrant', max_length=20),
        ),
    ]
