# Generated by Django 6.1.1 on 2026-10-02 11:15

from django.db import migrations, models


def confirm_old_accounts(apps, schema_editor):
    # Everyone who has an account so far logged in with a code sent to their email, so their email is proven.
    # They have no password yet: they set one with "forgot password" the first time.
    apps.get_model("accounts", "User").objects.update(email_verified=True)



class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_editor_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcode',
            name='purpose',
            field=models.CharField(choices=[('verify', 'Confirm email'), ('reset', 'Reset password')], default='verify', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(confirm_old_accounts, migrations.RunPython.noop),
    ]
