# Generated by Django 6.1.1 on 2026-10-01 13:19

from django.db import migrations, models

# Real official sites, checked by hand. The server gets them with `migrate`; admins can edit or add more.
SITES = [
    ("info", 1, "ГУВМ МВД России — иностранным гражданам",
     "https://xn--b1aew.xn--p1ai/mvd/structure1/Glavnie_upravlenija/guvm/inostrannim_grazhdanam",
     "Сайти расмии хадамоти муҳоҷирати Русия: қоидаҳои патент, бақайдгирӣ ва мӯҳлатҳо."),
    ("info", 2, "Закон № 115-ФЗ «О правовом положении иностранных граждан в РФ»",
     "https://www.consultant.ru/document/cons_doc_LAW_37868/",
     "Матни пурраи қонун (охирин таҳрир). Дар бораи патент — моддаи 13.3."),
    ("info", 3, "Госуслуги",
     "https://www.gosuslugi.ru/",
     "Хидматҳои давлатии Русия: навбат ба маркази муҳоҷират, санҷиши аризаҳо, ҷаримаҳо."),
    ("info", 4, "ФНС России — узнать ИНН",
     "https://service.nalog.ru/inn.do",
     "ИНН-и худро бифаҳмед — барои пардохти патент лозим аст."),
    ("info", 5, "Хадамоти муҳоҷирати Ҷумҳурии Тоҷикистон",
     "https://migration.tj/",
     "Сайти расмии Хадамоти муҳоҷирати Вазорати меҳнат, муҳоҷират ва шуғли аҳолӣ."),
    ("embassy", 1, "Посольство Республики Таджикистан в РФ",
     "https://tajembassy.ru/",
     "Сайти расмии сафорат дар Маскав: суроға, рақамҳо, хизматҳои консулӣ."),
]


def add_sites(apps, schema_editor):
    HelpContact = apps.get_model("support", "HelpContact")
    for kind, order, title, website, description in SITES:
        HelpContact.objects.get_or_create(website=website, defaults={"kind": kind, "order": order, "title": title, "description": description})


def remove_sites(apps, schema_editor):
    apps.get_model("support", "HelpContact").objects.filter(website__in=[site[3] for site in SITES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpcontact',
            name='kind',
            field=models.CharField(choices=[('info', 'Official site to read'), ('embassy', 'Embassy / consulate'), ('hotline', 'Hotline'), ('lawyer', 'Lawyer'), ('mvd_check', 'Official MVD check page'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.RunPython(add_sites, remove_sites),
    ]
