#!/usr/bin/env bash
# Opens another project of this server on a subdomain of king.tj, with HTTPS. Run as root:
#   bash /home/romin/muhojir/deploy/subdomain.sh pharma 8095     → https://pharma.king.tj shows the site on port 8095
# First add the subdomain in DNS (navjucloud → Управление DNS): Имя хоста = pharma, Тип = A, Значение = this server's IP.
# The project itself is not changed: nginx passes the visitors to its port. Running it again is safe.
# To remove one: rm /etc/nginx/sites-enabled/king-<name> && systemctl reload nginx
set -euo pipefail

BASE=king.tj
NAME=${1:-}
PORT=${2:-}
[ "$(id -u)" = 0 ] || { echo "Run this script as root."; exit 1; }
[[ "$NAME" =~ ^[a-z0-9]([a-z0-9-]*[a-z0-9])?$ ]] && [[ "$PORT" =~ ^[0-9]+$ ]] || {
  echo "Usage: bash $0 <name> <port>    e.g. bash $0 pharma 8095"; exit 1; }

HOST=$NAME.$BASE
CONF=/etc/nginx/sites-available/king-$NAME
CERT_DIR=/etc/letsencrypt/live/$HOST
SERVER_IP=$(hostname -I | awk '{print $1}')

curl -s -m 5 -o /dev/null "http://127.0.0.1:$PORT/" || { echo "Nothing answers on port $PORT. Start the project first."; exit 1; }
getent hosts "$HOST" >/dev/null || echo "Warning: $HOST is not in DNS yet (add an A record → $SERVER_IP); HTTPS will fail until it is."

# What every block does with the visitor: send them to the project, keeping the real address, HTTPS flag and WebSockets.
proxy() {
  cat <<NGINX
    client_max_body_size 20M;
    location / {
        proxy_pass http://127.0.0.1:$PORT;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade_king;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 120s;
    }
NGINX
}

write_nginx() {
  {
    echo "# $HOST → port $PORT: generated by deploy/subdomain.sh, do not edit here."
    if [ "$1" = https ]; then
      echo "server {"
      echo "    listen 80;"
      echo "    server_name $HOST;"
      echo "    location /.well-known/acme-challenge/ { root /var/www/certbot; }"
      echo "    location / { return 301 https://\$host\$request_uri; }"
      echo "}"
      echo "server {"
      echo "    listen 443 ssl http2;"
      echo "    server_name $HOST;"
      echo "    ssl_certificate $CERT_DIR/fullchain.pem;"
      echo "    ssl_certificate_key $CERT_DIR/privkey.pem;"
      echo "    ssl_protocols TLSv1.2 TLSv1.3;"
      proxy
      echo "}"
    else
      echo "server {"
      echo "    listen 80;"
      echo "    server_name $HOST;"
      echo "    location /.well-known/acme-challenge/ { root /var/www/certbot; }"
      proxy
      echo "}"
    fi
  } > "$CONF"
  ln -sf "$CONF" "/etc/nginx/sites-enabled/king-$NAME"
  if nginx -t 2>&1; then
    systemctl reload nginx
  else
    rm -f "/etc/nginx/sites-enabled/king-$NAME"
    echo "nginx found an error in the $HOST config; it is switched off, other sites are not affected."
    exit 1
  fi
}

cat > /etc/nginx/conf.d/king-upgrade-map.conf <<'NGINX'
# For the king.tj subdomains (deploy/subdomain.sh): pass WebSocket upgrades, keep normal requests normal.
map $http_upgrade $connection_upgrade_king {
    default upgrade;
    ''      close;
}
NGINX
mkdir -p /var/www/certbot

if [ -f "$CERT_DIR/fullchain.pem" ]; then
  write_nginx https
else
  write_nginx http
  command -v certbot >/dev/null || { apt-get update -qq && apt-get install -y -qq certbot; }
  # Uses the Let's Encrypt account made for king.tj; asks for an email and the terms only if there is none yet.
  if certbot certonly --webroot -w /var/www/certbot -d "$HOST" --deploy-hook "systemctl reload nginx"; then
    write_nginx https
  else
    echo "No certificate yet: $HOST works over http. Check its DNS record, then run this script again."
  fi
fi

if [ -f "$CERT_DIR/fullchain.pem" ]; then URL=https://$HOST; else URL=http://$HOST; fi
curl -sS -o /dev/null -w "$URL: HTTP %{http_code}\n" --resolve "$HOST:443:127.0.0.1" --resolve "$HOST:80:127.0.0.1" "$URL/" || true
echo "Done: $URL"
