# Generated by Django 6.1.1 on 2026-09-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawnews',
            name='summary',
            field=models.CharField(max_length=500),
        ),
    ]
