# Generated by Django 6.1.1 on 2026-09-30 18:56

import core.files
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_lawnews_summary_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='photo',
            field=models.FileField(blank=True, storage=core.files.private_storage, upload_to=core.files.document_photo_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'pdf']), core.files.validate_file_size]),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='remind_days_before',
            field=models.PositiveSmallIntegerField(choices=[(30, '30 days before'), (14, '14 days before'), (7, '7 days before'), (3, '3 days before'), (1, '1 day before')], default=7),
        ),
    ]
