# Generated by Django 6.1.1 on 2026-10-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_payments_and_migration_centers'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidestep',
            name='example',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='guidestep',
            name='where',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
