# Generated by Django 6.1.1 on 2026-10-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_document_types_and_centers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('language', 'Russian language'), ('history', 'History of Russia'), ('law', 'Basics of law')], max_length=20)),
                ('question', models.CharField(max_length=500)),
                ('listen_text', models.TextField(blank=True)),
                ('options', models.JSONField()),
                ('answer', models.PositiveSmallIntegerField()),
                ('explanation', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['section', 'order', 'id'],
            },
        ),
    ]
